Add a checkbox to the GE connection to optionally override the projec…
etiennestuder/teamcity-build-scan-plugin pull request #236
Opened 2023-05-01 15:26 UTC by clayburn

…t's configured GE URL

2023-05-01 15:41 UTC, clayburn commented on agent/src/main/resources/build-scan-init.gradle
> +            if (geUrl && geOverrideServerUrl) {
It is very tempting to try to combine this logic with the logic in the `if (!settings.pluginManager...)` block. I did not do so for this PR. But we could consider the following (pseudocode):

```
if plugin is not applied:
	apply plugin
    add auto injection value

if plugin was applied or if ge url is set and override is enabled:
	set server url
    set allow untrusted
    set publish always
    disable upload in backgroun
```

2023-05-02 13:09 UTC, etiennestuder requested changes

2023-05-02 13:09 UTC, etiennestuder commented on src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionConstants.java
> +
I would move this method below getAllowUntrustedServer for consistency.

2023-05-02 13:09 UTC, etiennestuder commented on src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseParametersProvider.java
> +            setParameter(OVERRIDE_EXISTING_SERVER_URL_CONFIG_PARAM, connectionParams.get(OVERRIDE_EXISTING_SERVER), params);
Same comment as abo ve. 'allowUntrusted' to come first.

2023-05-02 13:40 UTC, etiennestuder requested changes

2023-05-02 14:35 UTC, clayburn commented on agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
> +            } else if (Boolean.parseBoolean(getOptionalConfigParam(GE_OVERRIDE_EXISTING_SERVER_PARAM, runner))) {
Done ✅

2023-05-02 15:45 UTC, clayburn commented
@etiennestuder Everything here should now be addressed

2023-05-02 18:20 UTC, etiennestuder approved these changes
LGTM. Thanks for the work.

2023-05-02 19:06 UTC, merged